spring.application.name=notification-service
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
# Server Configuration
server.port=8085


# Mail / SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
#spring.mail.username=your-email@gmail.com
#spring.mail.password=your-16-character-app-password
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Eureka Client Configuration
#eureka.client.serviceUrl.defaultZone=http://localhost:8761/eureka/
