spring.application.name=api-gateway
server.port=8080
spring.data.redis.host=my-redis
spring.data.redis.port=6379
management.endpoints.web.exposure.include=*
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans

management.zipkin.tracing.endpoint=http://host.docker.internal:9411/api/v2/spans
# Management and Tracing Configuration
management.tracing.sampling.probability=1.0
#management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
spring.cloud.gateway.observability.enabled=true
spring.reactor.context-propagation=auto
# Optional: Include Trace and Span IDs in your standard application logs
logging.pattern.level=%5p [${spring.application.name}:%X{traceId:-}:%X{spanId:-}]
#logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
# Point to our Eureka Server
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
#start logging 
# 1. Turn on TRACE level logging for the Gateway routing logic
logging.level.org.springframework.cloud.gateway=TRACE

# 2. Turn on DEBUG level logging for the underlying reactive web framework
logging.level.org.springframework.http.server.reactive=DEBUG
logging.level.org.springframework.web.reactive=DEBUG

# 3. Enable Netty Wiretapping to print request details in the console
spring.cloud.gateway.httpserver.wiretap=true
spring.cloud.gateway.httpclient.wiretap=true
#end logging
# Enable locating services through Eureka
#spring.cloud.gateway.discovery.locator.enabled=true
#spring.cloud.gateway.discovery.locator.lower-case-service-id=true

# --- ROUTING RULES ---

# Route for Auth Service
spring.cloud.gateway.routes[0].id=auth-service
# lb:// means "Load Balance" using Eureka's registered service name
spring.cloud.gateway.routes[0].uri=lb://AUTH-SERVICE
# Match any request that starts with /auth/
spring.cloud.gateway.routes[0].predicates[0]=Path=/auth/**

# Route for Fake Protected Testing (Index 1)
spring.cloud.gateway.routes[1].id=test_protected_route
spring.cloud.gateway.routes[1].uri=https://jsonplaceholder.typicode.com
spring.cloud.gateway.routes[1].predicates[0]=Path=/todos/**
#spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://localhost:8081/auth/.well-known/jwks.json
spring.security.oauth2.resourceserver.jwt.jwk-set-uri=http://auth-service:8081/auth/.well-known/jwks.json
# Request Rate Limiter Filter Arguments
spring.cloud.gateway.routes[0].filters[0].name=RequestRateLimiter
# Number of tokens added per second
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.replenishRate=1
# Maximum token capacity allowed in a single burst
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.burstCapacity=20
# Number of tokens each request costs (defaults to 1 if omitted)
spring.cloud.gateway.routes[0].filters[0].args.redis-rate-limiter.requestedTokens=1
# Reference to your Spring Bean @Bean(name = "userKeyResolver")
spring.cloud.gateway.routes[0].filters[0].args.key-resolver=#{@userKeyResolver}