spring.application.name=auth-service
server.port=8081
# Eureka Client Configuration
#eureka.client.service-url.defaultZone=http://localhost:8761/eureka/
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.instance.prefer-ip-address=true
#spring.datasource.url=jdbc:mysql://localhost:3306/auth_db
spring.datasource.url=jdbc:mysql://host.docker.internal:3306/auth_db
spring.datasource.username=root
spring.datasource.password=root
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
# Management and Tracing Configuration
management.tracing.sampling.probability=1.0
#management.otlp.tracing.endpoint=http://localhost:4318/v1/traces
#management.otlp.tracing.transport=http
# Optional: Include Trace and Span IDs in your standard application logs
#logging.pattern.level=%5p [${spring.application.name}:%X{traceId:-}:%X{spanId:-}]
logging.pattern.level=%5p [${spring.application.name:},%X{traceId:-},%X{spanId:-}]
#management.endpoints.web.exposure.include=health,info,tracing,metrics,prometheus
management.endpoints.web.exposure.include=*
management.observations.http.server.requests.enabled=true
#management.tracing.propagation.type=W3C
# Force tracing filters to execute before Spring Security filters
#management.tracing.chaining.enabled=true
#spring.security.filter.order=100
#management.tracing.enabled=true
# Disable the Zipkin exporter so it doesn't block when offline
management.tracing.enabled=true
#management.zipkin.tracing.export.enabled=true
management.tracing.export.zipkin.enabled=true
#management.zipkin.tracing.endpoint=http://localhost:9411/api/v2/spans
#management.tracing.export.zipkin.endpoint=http://localhost:9411/api/v2/spans
management.zipkin.tracing.endpoint=http://host.docker.internal:9411/api/v2/spans
management.tracing.propagation.type=W3C
# Ensure Spring's internal MVC filter logs the observation context
logging.level.org.springframework.web.filter.ServerHttpObservationFilter=DEBUG

# Make sure Micrometer explicitly sets the logging context for Brave
#management.tracing.brave.bridge.enabled=true
management.tracing.brave.logging.mvc.enabled=true
logging.level.org.apache.tomcat.util.http.MimeHeaders=DEBUG
logging.level.org.springframework.web.servlet.DispatcherServlet=DEBUG
# Force local processing contexts to remain active without a registry export
#management.tracing.enabled=true
#management.tracing.sampling.probability=1.0

# Explicitly ensure the internal observation framework hooks the MDC mapper
management.observations.key-values.enabled=true
management.server.port=8084